# Generated by Django 3.2.9 on 2021-11-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='status',
        ),
    ]
