# Generated by Django 3.2.9 on 2021-11-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_state_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='folder',
        ),
    ]
