# Generated by Django 3.2.9 on 2021-11-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
